# Generated by Django 4.0.4 on 2022-06-01 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cricket_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchdetails',
            name='match_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchNo', to='cricket_app.matchno'),
        ),
        migrations.AlterField(
            model_name='matchdetails',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
