# Generated by Django 4.0.4 on 2022-06-01 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cricket_app', '0002_alter_matchdetails_match_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchdetails',
            name='match_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matchNo', to='cricket_app.matchno'),
        ),
        migrations.AlterField(
            model_name='playerdetails',
            name='best_wickets',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playerdetails',
            name='fifties',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playerdetails',
            name='hundreds',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playerdetails',
            name='strike_rate',
            field=models.FloatField(default=0),
        ),
    ]
