# Generated by Django 4.0.4 on 2022-06-01 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cricket_app', '0003_alter_matchdetails_match_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerdetails',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
